name: release-handling-workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Run release-please
        id: release-please-step
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug release outputs
        if: ${{ always() }}
        run: |
          echo "release_created: ${{ steps.release-please-step.outputs.release_created }}"
          echo "releases_created: ${{ steps.release-please-step.outputs.releases_created }}"
          echo "prs_created: ${{ steps.release-please-step.outputs.prs_created }}"
          echo "########################################################"
    outputs:
      release_created: ${{ steps.release-please-step.outputs.release_created }}
      release_tag: ${{ steps.release-please-step.outputs.tag_name }}
        
  pack-and-push:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ needs.release-please.outputs.release_tag }}
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack SDK
        working-directory: src/Spotify.Confidence.Sdk
        run: dotnet pack --configuration Release --no-build --output ../../nupkg

      - name: Pack OpenFeature Provider
        working-directory: src/Spotify.Confidence.OpenFeature
        run: dotnet pack --configuration Release --no-build --output ../../nupkg

      - name: Push to NuGet
        run: dotnet nuget push nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

